### ISSUE TITLE
Deployment option for Kubernetes

### ISSUE THREAD

**Issue by alexellis** [s8sg/faas-flow-minio-datastore#1]
Hi @s8sg it'd be good to have a deployment option for Kubernetes..

I saw you used our script from openfaas-cloud to setup Minio, you can use the same script we use for Helm to setup the configuration for Kubernetes too.

I'd also highly recommend pinning to a specific version of Minio from the tags on the Docker Hub to prevent breaking changes in Minio causing an unexpected error. 

Alex

**Comment by comradelemoncake** [comment]
I'd love to help out with this is it's something you're open to having outside help on!

**Comment by s8sg** [comment]
Sure go ahead. I haven’t tested faas-flow In Kubernetes fully, it is a good time to start that. If you need any help please let me know

**Comment by s8sg** [comment]
This is added as a part of https://github.com/s8sg/faas-flow-infra
