### ISSUE TITLE
Error When Building Docker Image

### ISSUE THREAD

**Issue by turnkey-commerce** [s8sg/faas-flow-minio-datastore#2]
I ran into an error when building the docker image for faas-flow with this datastore, something to do with the vendoring folder.  The error is shown below and happens when I try to go get the package:

```
...
Step 8/22 : RUN go get github.com/s8sg/faas-flow-minio-datastore
 ---> Running in 75d1e1a6cec1
# cd /go/src/github.com/s8sg/faas-flow-minio-datastore; git submodule update --init --recursive
fatal: No url found for submodule path 'vendor/github.com/minio/sha256-simd' in .gitmodules
package github.com/s8sg/faas-flow-minio-datastore: exit status 128
The command '/bin/sh -c go get github.com/s8sg/faas-flow-minio-datastore' returned a non-zero code: 1
```

I added the go get to the Dockerfile in the as such:

```
FROM openfaas/of-watchdog:0.5.3 as watchdog
FROM golang:1.13 as build

COPY --from=watchdog /fwatchdog /usr/bin/fwatchdog
RUN chmod +x /usr/bin/fwatchdog

RUN mkdir -p /go/src/handler
WORKDIR /go/src/handler
COPY . .

RUN go get github.com/s8sg/faas-flow-minio-datastore
...
```

Am I going about this the wrong way?  I noticed that particular folder in the vendor folder is empty.

**Comment by s8sg** [comment]
@turnkey-commerce Thanks for creating the issue, I'll take a look and get back to you soon

**Comment by s8sg** [comment]
@turnkey-commerce This is a example of how we are providing the library as `vendor`
https://github.com/s8sg/faas-flow-example/tree/master/conditional-branching

**Comment by turnkey-commerce** [comment]
Thanks @s8sg, I'll try to duplicate that way of vendoring instead of using go get in the Docker.

**Comment by turnkey-commerce** [comment]
Thanks again @s8sg, I was able to get it to work by vendoring.
